local H = require("spec_helper")
describe("heatmap core", function()
    local Heatmap = require("heatmap")
    describe("classify", function()
        it("returns 0 for no reading", function()
            assert.equals(0, Heatmap.classify(0, 40, "relative"))
            assert.equals(0, Heatmap.classify(nil, 40, "relative"))
            assert.equals(0, Heatmap.classify(-5, 0, "absolute"))
        end)
        it("shades relative to the baseline", function()
            assert.equals(1, Heatmap.classify(10, 40, "relative"))
            assert.equals(2, Heatmap.classify(20, 40, "relative"))
            assert.equals(2, Heatmap.classify(50, 40, "relative"))
            assert.equals(3, Heatmap.classify(51, 40, "relative"))
        end)
        it("uses fixed thresholds without a baseline and in absolute mode", function()
            assert.equals(1, Heatmap.classify(14, 0, "relative"))
            assert.equals(2, Heatmap.classify(15, 200, "absolute"))
            assert.equals(2, Heatmap.classify(60, 200, "absolute"))
            assert.equals(3, Heatmap.classify(61, 200, "absolute"))
        end)
    end)
    describe("weekdayShares", function()
        it("averages each weekday column over the window and normalises to the best", function()
            local days = {}
            for i = 1, 14 do days[i] = { minutes = (i % 7 == 0) and 60 or 30 } end
            local shares, raw = Heatmap.weekdayShares(days, 6, 2)
            assert.equals(1, shares[6])
            assert.equals(0.5, shares[0])
            assert.equals(60, raw[6])
        end)
        it("returns zeros without history", function()
            local shares = Heatmap.weekdayShares({}, 3)
            for col = 0, 6 do assert.equals(0, shares[col]) end
        end)
    end)
    describe("spans", function()
        it("shapes a run of months from its first weekday", function()
            local q = Heatmap.spanShape(2026, 7, 9, 2)
            assert.equals(92, q.days)
            assert.equals(3, #q.months)
            assert.equals("Jul", q.months[1].label)
            assert.equals("2026-07-01", q.start_date)
            assert.equals(14, q.weeks)
        end)
        it("rolls month numbers over and picks the range window", function()
            local wrap = Heatmap.spanFor("quarter", { year = 2026, month = 1, day = 5 }, 2)
            assert.equals("2025-11-01", wrap.start_date)
            assert.equals(365, Heatmap.spanFor("year", { year = 2026, month = 9 }, 2).days)
            assert.equals(30, Heatmap.spanFor("month", { year = 2026, month = 9 }, 2).days)
        end)
        it("maps a weekday to its column from the week start", function()
            assert.equals(0, Heatmap.weekdayCol(2, 2))
            assert.equals(6, Heatmap.weekdayCol(1, 2))
            assert.equals(0, Heatmap.weekdayCol(1, 1))
        end)
    end)
end)
