local H = require("spec_helper")
describe("spec helper", function()
    it("records paints", function()
        local bb = H.bb()
        bb:paintRect(1, 2, 3, 4, "black")
        bb:paintBorder(0, 0, 10, 10, 1, "gray")
        assert.equals(2, #bb.calls)
        assert.same({ "rect", 1, 2, 3, 4, "black" }, bb.calls[1])
        assert.equals(1, #H.only(bb, "border"))
    end)
    it("stubs text at six pixels a character", function()
        local T = require("ui/widget/textwidget")
        assert.equals(60, T:new{ text = "day streak" }:getSize().w)
    end)
    it("has the extra asserts", function()
        assert.has_no.errors(function() end)
        assert.is_function(print)
        assert.near(1.0, 1.0000001, 1e-3)
    end)
end)
